### PR TITLE
Add upstream timeouts

### LINKED ISSUE #26: COPS requests never time out
**Description**
In examining client logs from customers who require use of an upstream proxy, we see clients timing out their requests to the proxy but the proxy never timing out its request to COPS.  While this doesn't necessarily pose a resource starvation problem over time (because async waits are much lighter weight than threads), it would still be better to time out and clean up the client connections.  Plus it means that the proxy running in forward mode will just hang.

**Steps to reproduce**
* Run the proxy in forward mode with no upstream proxy when it requires one.
* The proxy hangs.

**Expected behavior**
The proxy times out.

**Environment**
 - frl-proxy version: 1.0.1
 - OS type and version: any

### PR DESCRIPTION
**Pull request by adobeDan**
## Summary
Add timeouts on the upstream calls to COPS.  This prevents hangs when running in forwarding mode, and prevents build-up of waiting requests in cache mode after the client has already closed their connection.

## Testing Steps
* Set up a debugging proxy like Charles.  Have it intercept calls to COPS and hold them on a breakpoint.
* Run the proxy in passthrough mode.
* If testing a debug build, set the environment variable FRL_PROXY_TIMEOUT to 10000 (for 10 seconds).
* Launch an app.

You will see the FRL proxy time out after 59 (or 10) seconds and return a failure to the client.

NOTE: This PR builds on the #25, so it should be merged after #25.  The proxy support makes it a lot easier to test.  Both PRs should be released at the same time.

Fixes #26

### CODE REVIEW

**Comment by adobeDan** [comment]
@adorton-adobe Do you have any time to test this little additional feature?  If not, I think I will merge it after testing on Windows (already tested on Mac).  It should be cross-platform but it can't hurt to test.

**Comment by adorton-adobe** [comment]
Yes, I can look at it today or tomorrow.

**Comment by adorton-adobe** [comment]
I set up a breakpoint in Charles. When I launch an app to trigger a request, the breakpoint pops up with the abort/execute dialog, but the request also seems to be going through to COPS anyway. I can't seem to trigger a real timeout to test this.

**Comment by adobeDan** [comment]
Set the timeout to be quite low, like 10 seconds.  Set the breakpoint on the response, not the request, because that will hold the response while the dialog is showing.  You will see the proxy time out and return to the client at which point the client will resubmit the request (because the proxy gives a 502 which is a temporary error so the client retries).  But that response will also hit the breakpoint, so you will see the proxy time out a second time.

**Comment by adorton-adobe** [comment]
I did exactly what you instructed, but I'm getting the same behavior. 

Here is my breakpoint config:

image

This is what pops up when I hit the breakpoint:

image

And this is the log for the last attempt:

```[2021-06-29][11:03:31][frl_proxy::proxy][INFO] Received request for /asnp/frl_connected/values/v2
[2021-06-29][11:03:31][frl_proxy::proxy][DEBUG] Received request method: POST
[2021-06-29][11:03:31][frl_proxy::proxy][DEBUG] Received request headers: {"connection": "Keep-Alive", "content-type": "application/json", "accept": "application/json", "user-agent": "NGL Client/1.25.0.7 (WINDOWS_64/10.0.19041.1) [2021-06-29T11:03:31.698-0600]", "x-api-key": "ngl_acrobat_dc1", "x-request-id": "Req-Id-eea4d053-79f8-41f0-9c89-b082dc8d4eb3", "x-session-id": "d59d3697-bc93-4d69-8163-da225d3e0c06.1624986211392", "content-length": "769", "host": "frl-proxy.brotsky.net:8443"}
[2021-06-29][11:03:31][frl_proxy::proxy][DEBUG] Received request body: {
        "appDetails" :
        {
                "currentAsnpId" : "",
                "nglAppId" : "AcrobatDC1",
                "nglAppVersion" : "12.0",
                "nglLibVersion" : "1.25.0.7"
        },
        "asnpTemplateId" : "TlRVNFlUaGhZek10WWpNeE5pMDBZemN5TFRreU5XTXROR00xTW1FNFltUTFZekExe31hZDg0YjI1Zi02YjA5LTRmNzEtYWY2Mi1kODBmZGUzNDAyMjA",
        "deviceDetails" :
        {
                "currentDate" : "2021-06-29T11:03:31.674-0600",
                "deviceId" : "d5a9c61202a6a0a996ab06d17af7278089c07a6f6afe619350491c7681714f1b",
                "enableVdiMarkerExists" : false,
                "isOsUserAccountInDomain" : true,
                "isVirtualEnvironment" : false,
                "osName" : "WINDOWS_64",
                "osUserId" : "19edbd0af365bab10e6ef78201e9e28de8f1b465db27ad8a0ae800ef1de4b936",
                "osVersion" : "10.0.19041.1"
        },
        "npdId" : "NTU4YThhYzMtYjMxNi00YzcyLTkyNWMtNGM1MmE4YmQ1YzA1",
        "npdPrecedence" : 90
}
[2021-06-29][11:03:31][frl_proxy::proxy][INFO] Received request id: Req-Id-eea4d053-79f8-41f0-9c89-b082dc8d4eb3
[2021-06-29][11:03:31][frl_proxy::proxy][INFO] Forwarding request Req-Id-eea4d053-79f8-41f0-9c89-b082dc8d4eb3 to COPS at https://lcs-cops-stage.adobe.io
[2021-06-29][11:03:31][frl_proxy::proxy][INFO] Connecting via proxy: http://127.0.0.1:8888
[2021-06-29][11:03:32][frl_proxy::proxy][INFO] Received success response (200) from COPS
[2021-06-29][11:03:32][frl_proxy::proxy][DEBUG] Received success response headers {"server": "openresty", "date": "Tue, 29 Jun 2021 17:03:32 GMT", "content-type": "application/json;charset=UTF-8", "transfer-encoding": "chunked", "connection": "keep-alive", "x-request-id": "Req-Id-eea4d053-79f8-41f0-9c89-b082dc8d4eb3", "vary": "accept-encoding"}
[2021-06-29][11:03:32][frl_proxy::proxy][DEBUG] Received success response body {"adobeCertSignedValues":{"signatures":{"signature1":"asnQghTpxQSivhmSjWXu7xczYkEZJSsmeYyhXPLQMQJ7TT24xTcUlldT6ZSLqCGARaMpm1bzF01tA6xAXE4ZjiJ42DrT5yUP-z0tvEKy3GGSi4JWMQmVEN6DVvQs99QHGJ1R-6czB-KWmqHbdw-l8jclkJlUxrmso43c9I9cY8bsqKak8YT77FcJh6yWr1YATXHTo--RYJkn1nQMPLQwszNRKaQS-SZ88P4nVjeU0HHoZPbN6tGByaOdmoEMZFFbZr6hE_VKqvLMyM4PTV7_gxFprOfiD6w4eIOAvE6mST76eKwsK_ygtn5nO-6wV_baFjznuu5X4DAL9Vtfb9fcD3X2jY7mqFCa4r50k8igxvZFJ1QGgbGXxqNMrY26wPbLxgR0f1JJIcnPiMFU6DHwTFBb-6H1NVXeOnsfJYUh6H9E_EyKIyHaiSd6Pz06THiJnilIeHEK7iYO_g7XYjFd43WflzNzBIx28zfdk5j5QdC16yPOJK2gznt3fTYwHJklK3kObKwneIN4Spb18QVvFOk2atYeKDGduJ7yD9KdfkFdILc2cJNoo26ZtrdblbDuci0hRfQKb9mJW_kadwPLBX1lnyp014D-p2AGHgXGe0rofjZE3NwUq0rJjJPFmDz80sXUAKWn99lnSE-e3ucYINlaWsSHKcEJv3eVGy5qIWg","signature2":"wuhq6jtAOi76SGMznvc6xdWu-_1xL9AwVthSgqKt3IzNOMKW1ArHmqlhDtxEV73qBG9_JKyftVG57-8P4mUM_nEjHN8iF-T6eU-Z8Gg0KSb2TRRG28RdqW-AK4u6CZ_FlXBki3GZv_yv76bGDD_IeN8cosIzze9TOBCxlXvwjTKZdkng8vPLjbMvWicTN4gkJOXpMIDoEjUcQvdgQBsMJ2bt833e6_CGGjzMagbZzHdguxiNjHP2YHtG--N2nDoCxTEo60zCIKXC20tUBXFYfYmLbrnFfVnexP_sC5nZ0J0UK83_0aQkec4v9-ANAgVianHcjHDcKMQTI-oPGBcukjuMLZYHHnZtW1HPVYSVR1gDEynDDUk75RQgJrjGvLPrt6axYmFyAtcC7dUF3DucjpYyEUIOraCssFrwwW8dI0C-KECfq0coUJhiPkMkFiBnLnqve1Yr3HgpmmbdX3Bm7nF9EF6S29AjSifqDPEr3_4Ijg0PS6gccvt8N9J3KEKMd9arD5z8Z_hgL8VMNZ6wqkRuYOns-P3EhPAA9cMWIPQopWMsQXdsiBKPEZBUU7tQKYo-HDMuuzhG_Y87vkJPvUsMV36kW3OWKVgV9xKGDbj4AjVAZGABneX67ZNphmcaM-nVCY6G51Pe9_DHOiT97Q-5BRamCK2KibBRuBzuT9I"},"values":{"licenseExpiryTimestamp":"1701673201000","enigmaData":"{\\\"productId\\\":591,\\\"serialKey\\\":\\\"159142360940313991274400\\\",\\\"clearSerialKey\\\":null,\\\"locale\\\":\\\"ALL\\\",\\\"associatedLocales\\\":\\\"ALL\\\",\\\"platform\\\":0,\\\"isk\\\":5914137,\\\"customerId\\\":0,\\\"deliveryMethod\\\":3,\\\"pc\\\":true,\\\"rb\\\":true}","graceTime":"8553600000","createdForVdi":"false","profileStatus":"PROFILE_AVAILABLE","effectiveEndTimestamp":"1693119601000","licenseExpiryWarningStartTimestamp":"1701068401000","nglLibRefreshInterval":"86400000","licenseId":"612DBE59ED9CA8267E0B","licensedFeatures":"[\\\"Acrobat_11.0\\\",\\\"Acrobat_Base_10.0\\\",\\\"Acrobat_Base_11.0\\\",\\\"Acrobat_Base_12.0\\\",\\\"Acrobat_Base_17.0\\\",\\\"Acrobat_Distiller_10.0\\\",\\\"Acrobat_Distiller_11.0\\\",\\\"Acrobat_Distiller_12.0\\\",\\\"Acrobat_Distiller_17.0\\\",\\\"Acrobat_Professional_10.0\\\",\\\"Acrobat_Professional_11.0\\\",\\\"Acrobat_Professional_12.0\\\",\\\"Acrobat_Professional_17.0\\\",\\\"AMT_SUBSCRIPTION_6.0\\\",\\\"Euclid_Base_1.0\\\"]","appRefreshInterval":"86400000","appEntitlementStatus":"SUBSCRIPTION"}},"customerCertSignedValues":{"signatures":{"customerSignature2":"f4KyjicI58w5Mxr8MgU6pc0pKVnY1pny0dx_FV_IQ01XYdO-tWhqbM6biaur3Cu6sI404Up23ZLMYMQW1yNZkVd0ZJgvNBWoFonfmhvT-sbkY5KgFY3uOGAXq0a517jYiV9LenXRKPPQypc0jE7XibVpkGaiY9nyKlbZ4PpOi0E3Tbv4sAlv3-IUYJv2KGfAMovwxUkTYwA5VanM0T0n325TRq6A7-sREKgb0gmKqTGzXWX84Qjng2YWo4LrnfufH_V4PNhsWrqfw_Q9FA_ueoSL_gfwssF1ZHxCLZrf7KVS6L55FWqPqiD3WHtdXVXcWY0R8BH1ipXsX3uY3vGS9VFkC4SGfnnx6xvSSUhf0m-5i5iWWE5_SN-u8GiyEGVOBVXQ5lxHpBapG_LNXajS_hkYbCCVyr5M-JisOxP7uAkhfHYYi0dQ7zMQUghsfZsPiKBk-96r222BZIX2JXAC0OaS5h-M_XqKES3asY8JNO6zPZMoG9sdlG_N4wZarsKqCqvcz0qrnaxTmFS7O1ttIJwnl5iAeSuJtGvDv14suC8SJ_1uoLkilVj5ux98zugIApbHKap2JLmcpNjkRZSmW5CgLr5JTIfN32_jZ9rMmUcQApHYX9o1gk6kVxro9tnOpumZLC8Ngh4-qSBhVvSvBVFGb7HyDGdx8D1rUH29szc","customerSignature1":"U3TG8WQc0G-prxGGXun0UAcTsiZQZa-g6_SIGKtnPb5ZG3Q3bsu-N_TQRfnKOyHxk1n1OZgAQA_gTFFXLe0Uqt2_11ZUpOmffcT4eFD1uXxRfDF3BtBcz1gykX0aCvB8qhOGGNTeLk3xUpprH4AeaRCkV2mz24cNN3iwVH7BYNXgRT9gLOQNcPXhW51JSLJEKSrw4kJpQd-m0pYHlsU_EcT-0PQORg3jngPRn8_eYWdoch-bA3njChV_WCalG9kAWB4jZ4mkW7_uMANavaZIAgeXK3_rWDrcwZlC74iIeokVdRCH0f7J9wth1ipSJtgIyWFcYunTG8JaPvrTkNA5aY71xg6MGQRU9fpPLp-OYwXPksnivIlUBPVPtuoXb_TF3x45AtM6UOkdD-65XNcnSv94-xOTY_5l9HpgSltSPeJPIp7xKuUhKUKlpZg-Puz4z0vTSJi2MgVVyzaY5i9M8aRsMmf9F1qkk49CysYU5YXyMEzpzO_moguRKhk5p8VBueWcyyWB52nHK3-XX4faD6hfvienC09mff6QHTfwpwubhZjFTPSVqX3yER7CiJV4SHx4DCC0HbHZFpKhpgCkqFDyUOkfRGL3fiL3XKxlTqADMwwF5cdq26k72vFv0H8Oq5TFzNHOxcYkdvr9EUh17kXxJkRfQ1_K7MoLXP2SS0w"},"values":"eyJucGRJZCI6Ik5UVTRZVGhoWXpNdFlqTXhOaTAwWXpjeUxUa3lOV010TkdNMU1tRTRZbVExWXpBMSIsImFzbnBJZCI6IjQzNmFiMDJmLTlmNGItNDUzNC1iNTBlLTI5ODdjZWEyNzI0MiIsImNyZWF0aW9uVGltZXN0YW1wIjoxNjI0OTg2MjEyMjI2LCJjYWNoZUxpZmV0aW1lIjo3NjY4Njk4ODc3NCwicmVzcG9uc2VUeXBlIjoiRlJMX0lOSVRJQUwiLCJjYWNoZUV4cGlyeVdhcm5pbmdDb250cm9sIjp7Indhcm5pbmdTdGFydFRpbWVzdGFtcCI6MTcwMTA2ODQwMTAwMCwid2FybmluZ0ludGVydmFsIjo4NjQwMDAwMH0sInByZXZpb3VzQXNucElkIjoiNzIxMTA1MjAtM2JlNC00NWQ0LTk0MzItZTljYzA4N2E4ZTU1IiwiZGV2aWNlSWQiOiJkNWE5YzYxMjAyYTZhMGE5OTZhYjA2ZDE3YWY3Mjc4MDg5YzA3YTZmNmFmZTYxOTM1MDQ5MWM3NjgxNzE0ZjFiIiwib3NVc2VySWQiOiIxOWVkYmQwYWYzNjViYWIxMGU2ZWY3ODIwMWU5ZTI4ZGU4ZjFiNDY1ZGIyN2FkOGEwYWU4MDBlZjFkZTRiOTM2IiwiZGV2aWNlRGF0ZSI6IjIwMjEtMDYtMjlUMTE6MDM6MzEuNjc0LTA2MDAiLCJzZXNzaW9uSWQiOiJkNTlkMzY5Ny1iYzkzLTRkNjktODE2My1kYTIyNWQzZTBjMDYuMTYyNDk4NjIxMTM5Mi9TVUJTRVFVRU5UIn0"}}```

**Comment by adobeDan** [comment]
Hmmmm.  So I can't repro this problem: it works for me using fry-proxy on both local and remote machines connecting to a Windows Charles proxy with the breakpoint set.  So I think you must have a misconfiguration somewhere.  Be sure you turn off local proxying in Charles (in the Proxy menu make sure there's no check against "Windows Proxy"), because that can confuse things.  Also maybe try using a prod license, rather than a stage license.

**Comment by adorton-adobe** [comment]
I've emailed you those items. I'm also using a debug build with the timeout env var.

image

If you've tested this enough we can probably move forward. It has to be an issue with my Charles config. I wonder if enabling SSL proxying would help.

**Comment by adobeDan** [comment]
Yes, turning on SSL proxying is absolutely required, otherwise the breakpoint cannot operate!  I'm going to merge and put out a pre-release while I work on the doc update.  But it would be great to get this working on your machine :).

**Pull request merged**
